post http://localhost:3000/register/ 
Content-Type: application/json

{
    "username":"adam_richard",
    "password":"richard_567",
    "name":"Adam Richard",
    "gender":"male"
}

###
post http://localhost:3000/login/ 
Content-Type: application/json 

{
    "username":"JoeBiden",
    "password":"biden@123"
}

###

GET http://localhost:3000/user/tweets/feed/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.ePvCHOOWZx2dOk2whRKI7AUgwjX8Zc_bY2TmvCLecMw
